### ISSUE TITLE
BackgroundModelDivergenceSnO-system

### ISSUE THREAD

**Issue by drs378** [MingChiangChang/pyPhaseLabel#3]
Including the background model with the parameter:

bg = BackgroundModel(Q, EQ(), 5)

will cause the background to not model well even after 2000 iterations

**Comment by MingChiangChang** [comment]
The `BackgroundModel`'s constructor looks like this

function BackgroundModel(
                 **x** # _The x axis,_
                 **k** # _The kernal choice_
                 **l** # _The length scale of the kernal,_
                 **λ** _# The regularizer, the penalty term is \sum λ*(fitted parameter);_
                **rank_to**l)

How the background model works:
It will take the kernel, the length scale and x values to construct a so-called Gram matrix. The background is then constructed by the linear combination of each row/column of the matrix. To lower the computational cost, SVD is performed and only those basis with singular values larger than rank_tol will be selected.

**Proposed solution:**
For background to stabilize, try doing
`bg = BackgroundModel(Q, EQ(), 5, 100)`
Having the lengthscale to be 5 can allow background to fit to small peaks and usually will make it to have more free parameters to fit, can do
`bg = BackgroundModel(Q, EQ(), 10, 100, rank_tol=1E-4)` (default tol is 1E-6)
to speed up the algorithm and prevent overfitting of background.
