### ISSUE TITLE
Module load fail 'optimize _with_uncertainty! not defined'

### ISSUE THREAD

**Issue by drs378** [MingChiangChang/pyPhaseLabel#4]
`----> 1 from .wrapper import evaluate_obj, optimize_phase, create_phases, fit_amorphous, optimize_all
      2 
      3 from julia.Main import CrystalPhase, PhaseModel, BackgroundModel, EQ, Wildcard # Important structs
      4 from julia.Main import Lorentz, Gauss, PseudoVoigt, FixedPseudoVoigt           # Peak Profile objects
      5 

~/pyPhaseLabel/wrapper.py in <module>
     12 from pathlib import Path
     13 
---> 14 Main.include(str(dir_path / "python_mod.jl"))
     15 Main.include(str(dir_path / "startup.jl"))
     16 

ImportError: <PyCall.jlwrap (in a Julia function called from Python)
JULIA: LoadError: UndefVarError: optimize_with_uncertainty! not defined`

**Comment by MingChiangChang** [comment]
Try updating your julia packages.

**Comment by drs378** [comment]
That worked. You're the man!
