### ISSUE TITLE
Julia domain error when invoking uncertainty estimates

### ISSUE THREAD

**Issue by drs378** [MingChiangChang/pyPhaseLabel#5]
```
---> 50         opm, unc_est = optimize_phase(pm, Q, I, maxiter=2000, gives_uncertatinty=True)
     51 #         SnO
     52         a0,b0,c0 = opm.CPs[0].cl.a,opm.CPs[0].cl.b,opm.CPs[0].cl.c

~/pyPhaseLabel/wrapper.py in optimize_phase(phasemodels, x, y, std_noise, mean_θ, std_θ, objective, method, maxiter, regularization, gives_uncertatinty, verbose, tol)
     83     assert objective in OBJ_LST
     84     if gives_uncertatinty:
---> 85         return optimize_with_uncertainty(phasemodels, x, y,
     86                 std_noise, mean_θ, std_θ,
     87                 method=method, objective=objective, maxiter=maxiter,

RuntimeError: <PyCall.jlwrap (in a Julia function called from Python)
JULIA: DomainError with -1.9151198159327062e-5:
sqrt will only return a complex result if called with a complex argument. Try sqrt(Complex(x)).
```

**Comment by drs378** [comment]
Also, Is the uncertainty estimates just a dictionary like the optimized phase model? If I want the errors on the LPs is the call

`
opm, unc_est = optimize_phase(pm, Q, I, maxiter=2000, gives_uncertainty=True)


da,db,dc = unc_est.CPs[0].a,  unc_est.CPs[0].b,  unc_est.CPs[0].c
`

**Comment by MingChiangChang** [comment]
Try doing a little bit more steps. Having negative values in the diagonal of Hessian means that it is not at a local minimum. (generally) Another potential solution is to lower the values for std_\theta, cuz this will make the problem more convex.

It is an array. Take 2 phase with phase 1 as tetragonal and phase 2 as cubic for example, unc_est=[phase_1_a, phase_1_c, phase_1_activation, phase_1_peak_width, phase_2_a, phase_2_activation, phase_2_peak_width].

**Comment by drs378** [comment]
hmmm. I tried both upping the max iterations and reducing the std_theta values but it remains to be problematic... I might bug you about it later.

**Comment by MingChiangChang** [comment]
It is hard for the optimization to converge for amorphous data. Now the returned uncertainty is variance instead to prevent domain error. Check for negative value then take the square root to get uncertainty estimates.
