### ISSUE TITLE
Would love for the Hessian errors to be an array of size 6

### ISSUE THREAD

**Issue by drs378** [MingChiangChang/pyPhaseLabel#6]
I am working on an H5 constructor for the fits so the data is formatted well. It's hard to filter based on crystal system. 

example:

`opm, unc_est = optimize_phase(pm, x, I, maxiter=2000, gives_uncertatinty=True)`

where unc_est is an array of arrays where it's [n,6] or however many terms are in the hessian

**Comment by MingChiangChang** [comment]
It now return as [n*6] list. (Not sure how pyjulia transform Julia matrix so I keep it to be 1d)
The symmetry-constrained a,b,c have the same uncertainty and the lattice angles that are set to 90 have 0 uncertainty.

**Comment by MingChiangChang** [comment]
Now the function returns [n*8] array
uncertainty = [1a, 1b, 1c, 1alpha, 1beta, 1gamma, 1act, 1width, 2a, 2b, 2c ...]
