### ISSUE TITLE
Request for "constant" background from user input

### ISSUE THREAD

**Issue by drs378** [MingChiangChang/pyPhaseLabel#7]
Would love to have a "background estimate" or something that could be hard coded into the optimization model. We may want to do this in the future anyways but relying on MCBL or approximations will result in failure. I think the background model introduces too many parameters so we over fit...

**Comment by MingChiangChang** [comment]
The latest commit provide `FixedBackground` option. Update the Julia packages before using.
See `README.md` for details.
